# Generated by Django 2.1.4 on 2019-03-29 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=40, unique=True)),
                ('content', models.TextField()),
                ('jieba_content', models.TextField()),
                ('score', models.BigIntegerField()),
                ('create_time', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'computer_comment',
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('computer_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('img_url', models.CharField(max_length=255)),
                ('param', models.TextField()),
                ('if_spider', models.BooleanField(default=0)),
                ('good_rate', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'computer',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=255)),
                ('count', models.CharField(max_length=200)),
                ('computer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Computer')),
            ],
            options={
                'db_table': 'computer_tag',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Computer'),
        ),
    ]
